# Generated by Django 5.1.3 on 2024-11-20 17:18

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('skyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=500)),
                ('content', models.TextField()),  # Content 필드 추가
                ('rdate', models.DateTimeField)
        ],
    ),
]